server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:travel-agency-command-side}
    
  threads:
    virtual:
      enabled: true
  
  sql:
    init:
      mode: always
      
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
    producer:
      properties:
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/travels_write_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:user1234}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 2000
      keepalive-time: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

kafka:
  topics:
    bookings:
      name: ${TOPIC_BOOKINGS}
      partitions: 3
      replicas: 1
    hotels:
      name: ${TOPIC_HOTELS}
      partitions: 3
      replicas: 1
  outbox:
    poll-interval: 1000
    batch-size: 50
    alert-after-retries: 5